// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using software.database.Provider;

namespace software.database.Migrations
{
    [DbContext(typeof(SoftwareDefautTable))]
    [Migration("20231214102441_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("software.database.System.erp_don_hang_ban_chi_tiet_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("chiet_khau")
                        .HasColumnType("int");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("don_gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("id_chiet_khau")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_don_hang")
                        .HasColumnType("bigint");

                    b.Property<long>("id_san_pham")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("so_luong")
                        .HasColumnType("bigint");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<decimal?>("thanh_tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_don_hang_ban_chi_tiet");
                });

            modelBuilder.Entity("software.database.System.erp_don_hang_ban_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("dia_chi_cu_the_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dia_chi_cu_the_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_don_vi_van_chuyen")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_quan_khach_hang_dat")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_quan_khach_hang_nhan")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_tinh_khach_hang_dat")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_tinh_khach_hang_nhan")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_ty_le_vat")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_ty_le_vat_van_chuyen")
                        .HasColumnType("bigint");

                    b.Property<string>("last_name_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("loai_chuyen_khoan")
                        .HasColumnType("int");

                    b.Property<long?>("loai_don_hang")
                        .HasColumnType("bigint");

                    b.Property<string>("ma_don_van_chuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_dat_hang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_du_kien_giao")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("phuong_thuc_thanh_toan")
                        .HasColumnType("int");

                    b.Property<int?>("so_ngay_du_kien_giao")
                        .HasColumnType("int");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<decimal?>("thanh_tien_sau_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("thanh_tien_truoc_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("thanh_tien_van_chuyen_sau_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("thanh_tien_van_chuyen_truoc_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("tien_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("tien_thue_van_chuyen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("trang_thai_thanh_toan")
                        .HasColumnType("bit");

                    b.Property<bool?>("trang_thai_xuat_hang")
                        .HasColumnType("bit");

                    b.Property<int?>("ty_le_vat")
                        .HasColumnType("int");

                    b.Property<int?>("ty_le_vat_van_chuyen")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_don_hang_ban");
                });

            modelBuilder.Entity("software.database.System.erp_don_hang_mua_chi_tiet_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("chiet_khau")
                        .HasColumnType("int");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("don_gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("id_chiet_khau")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_don_hang")
                        .HasColumnType("bigint");

                    b.Property<long>("id_san_pham")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("so_luong")
                        .HasColumnType("bigint");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<decimal?>("thanh_tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_don_hang_mua_chi_tiet");
                });

            modelBuilder.Entity("software.database.System.erp_don_hang_mua_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("dia_chi_cu_the_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dia_chi_cu_the_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_quan_khach_hang_dat")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_quan_khach_hang_nhan")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_tinh_khach_hang_dat")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_tinh_khach_hang_nhan")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_ty_le_vat")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_ty_le_vat_van_chuyen")
                        .HasColumnType("bigint");

                    b.Property<string>("last_name_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("loai_don_hang")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_dat_hang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_du_kien_giao")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_khach_hang_dat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_khach_hang_nhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("phuong_thuc_thanh_toan")
                        .HasColumnType("int");

                    b.Property<int?>("so_ngay_du_kien_giao")
                        .HasColumnType("int");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<decimal?>("thanh_tien_sau_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("thanh_tien_truoc_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("thanh_tien_van_chuyen_sau_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("thanh_tien_van_chuyen_truoc_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("tien_thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("tien_thue_van_chuyen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("trang_thai_thanh_toan")
                        .HasColumnType("bit");

                    b.Property<bool?>("trang_thai_xuat_hang")
                        .HasColumnType("bit");

                    b.Property<int?>("ty_le_vat")
                        .HasColumnType("int");

                    b.Property<int?>("ty_le_vat_van_chuyen")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_don_hang_mua");
                });

            modelBuilder.Entity("software.database.System.erp_don_vi_van_chuyen_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_don_vi_van_chuyen");
                });

            modelBuilder.Entity("software.database.System.erp_loai_nhap_xuat_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("loai_nhap_xuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nguon")
                        .HasColumnType("int");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_loai_nhap_xuat");
                });

            modelBuilder.Entity("software.database.System.erp_nhap_kho_chi_tiet_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("id_phieu_nhap")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_san_pham")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("so_luong")
                        .HasColumnType("bigint");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_nhap_kho_chi_tiet");
                });

            modelBuilder.Entity("software.database.System.erp_nhap_kho_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("id_kho")
                        .HasColumnType("bigint");

                    b.Property<long?>("loai_nhap")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_nhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_nhap_kho");
                });

            modelBuilder.Entity("software.database.System.erp_xuat_kho_chi_tiet_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("id_phieu_xuat")
                        .HasColumnType("bigint");

                    b.Property<long>("id_san_pham")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("so_luong")
                        .HasColumnType("bigint");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_xuat_kho_chi_tiet");
                });

            modelBuilder.Entity("software.database.System.erp_xuat_kho_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("id_kho")
                        .HasColumnType("bigint");

                    b.Property<long?>("loai_xuat")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_xuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("erp_xuat_kho");
                });

            modelBuilder.Entity("software.database.System.sys_banner_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_mobi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_web")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_banner");
                });

            modelBuilder.Entity("software.database.System.sys_color_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_color");
                });

            modelBuilder.Entity("software.database.System.sys_dieu_khoan_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<int?>("stt")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_dieu_khoan");
                });

            modelBuilder.Entity("software.database.System.sys_don_vi_tinh_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_don_vi_tinh");
                });

            modelBuilder.Entity("software.database.System.sys_file_upload_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("file_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("file_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_file_upload");
                });

            modelBuilder.Entity("software.database.System.sys_group_user_db", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<int?>("type_user")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_group_user");
                });

            modelBuilder.Entity("software.database.System.sys_group_user_detail_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("id_group_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sys_group_user_detail");
                });

            modelBuilder.Entity("software.database.System.sys_group_user_role_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("controller_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_controller_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_group_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sys_group_user_role");
                });

            modelBuilder.Entity("software.database.System.sys_kho_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_kho");
                });

            modelBuilder.Entity("software.database.System.sys_lien_ket_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<int?>("stt")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_lien_ket");
                });

            modelBuilder.Entity("software.database.System.sys_loai_san_pham_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_loai_san_pham");
                });

            modelBuilder.Entity("software.database.System.sys_ngan_hang_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("so_tai_khoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_ngan_hang");
                });

            modelBuilder.Entity("software.database.System.sys_nhan_hieu_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_nhan_hieu");
                });

            modelBuilder.Entity("software.database.System.sys_quan_huyen_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("id_quoc_gia")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_tinh")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_khong_dau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_quan_huyen");
                });

            modelBuilder.Entity("software.database.System.sys_quoc_gia_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_khong_dau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_quoc_gia");
                });

            modelBuilder.Entity("software.database.System.sys_san_pham_chi_tiet_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("gia_ban")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("hinh_anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_color")
                        .HasColumnType("bigint");

                    b.Property<string>("id_san_pham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_khuyen_mai")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_noi_bac")
                        .HasColumnType("bit");

                    b.Property<string>("mo_ta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qr_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_san_pham_chi_tiet");
                });

            modelBuilder.Entity("software.database.System.sys_san_pham_db", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("hinh_anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_don_vi_tinh")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_loai_san_pham")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_nhan_hieu")
                        .HasColumnType("bigint");

                    b.Property<string>("ma_san_pham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("ten_san_pham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_san_pham");
                });

            modelBuilder.Entity("software.database.System.sys_size_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_size");
                });

            modelBuilder.Entity("software.database.System.sys_tag_user_db", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_tag_user");
                });

            modelBuilder.Entity("software.database.System.sys_template_mail_db", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("template")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_template_mail");
                });

            modelBuilder.Entity("software.database.System.sys_thong_tin_website_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("dia_chi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_footer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_youtube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link_facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link_instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link_linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link_youtube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("so_dien_thoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_thong_tin_website");
                });

            modelBuilder.Entity("software.database.System.sys_tinh_thanh_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("id_quoc_gia")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_khong_dau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_tinh_thanh");
                });

            modelBuilder.Entity("software.database.System.sys_type_mail_db", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_type_mail");
                });

            modelBuilder.Entity("software.database.System.sys_user_db", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("expiration_date_reset_pass")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("phuong_thuc_thanh_toan")
                        .HasColumnType("int");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("token_reset_pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("type")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("software.database.System.sys_user_nhan_hang_db", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("dia_chi_cu_the")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("id_quan")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_tinh")
                        .HasColumnType("bigint");

                    b.Property<string>("id_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("sys_user_nhan_hang");
                });

            modelBuilder.Entity("software.database.System.sys_vat_db", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status_del")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("value")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("sys_vat");
                });
#pragma warning restore 612, 618
        }
    }
}
